<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=11"/>
<meta name="generator" content="Doxygen 1.9.6"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>VirtualBox Main API: IDHCPGroupCondition Interface Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr id="projectrow">
  <td id="projectalign">
   <div id="projectname">VirtualBox Main API
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.6 -->
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(function() {
  initMenu('',false,false,'search.php','Search');
});
/* @license-end */
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-attribs">Public Attributes</a> &#124;
<a href="interface_i_d_h_c_p_group_condition-members.html">List of all members</a>  </div>
  <div class="headertitle"><div class="title">IDHCPGroupCondition Interface Reference</div></div>
</div><!--header-->
<div class="contents">
<div class="dynheader">
Inheritance diagram for IDHCPGroupCondition:</div>
<div class="dyncontent">
 <div class="center">
  <img src="interface_i_d_h_c_p_group_condition.png" alt=""/>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a id="pub-methods" name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a0a92d2008c3871d6ca8b13c4f5ebe624"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_i_d_h_c_p_group_condition.html#a0a92d2008c3871d6ca8b13c4f5ebe624">remove</a> ()</td></tr>
<tr class="memdesc:a0a92d2008c3871d6ca8b13c4f5ebe624"><td class="mdescLeft">&#160;</td><td class="mdescRight">Remove this condition from the group.  <br /></td></tr>
<tr class="separator:a0a92d2008c3871d6ca8b13c4f5ebe624"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a id="pub-attribs" name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr class="memitem:a77f4e6ed9303da46c48c592bc3646470"><td class="memItemLeft" align="right" valign="top">attribute boolean&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_i_d_h_c_p_group_condition.html#a77f4e6ed9303da46c48c592bc3646470">inclusive</a></td></tr>
<tr class="memdesc:a77f4e6ed9303da46c48c592bc3646470"><td class="mdescLeft">&#160;</td><td class="mdescRight">Whether this is an inclusive or exclusive group membership condition.  <br /></td></tr>
<tr class="separator:a77f4e6ed9303da46c48c592bc3646470"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6c44c595fc7fbc63402b1ae2bda3985d"><td class="memItemLeft" align="right" valign="top">attribute <a class="el" href="_virtual_box_8idl.html#ad64816f3f460618a142d3ec78348668f">DHCPGroupConditionType</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_i_d_h_c_p_group_condition.html#a6c44c595fc7fbc63402b1ae2bda3985d">type</a></td></tr>
<tr class="memdesc:a6c44c595fc7fbc63402b1ae2bda3985d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Defines how the <a class="el" href="interface_i_d_h_c_p_group_condition.html#aee79bc725669f841f5bb2bf1dd087e43">IDHCPGroupCondition::value</a><b></b> is interpreted.  <br /></td></tr>
<tr class="separator:a6c44c595fc7fbc63402b1ae2bda3985d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aee79bc725669f841f5bb2bf1dd087e43"><td class="memItemLeft" align="right" valign="top">attribute wstring&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="interface_i_d_h_c_p_group_condition.html#aee79bc725669f841f5bb2bf1dd087e43">value</a></td></tr>
<tr class="memdesc:aee79bc725669f841f5bb2bf1dd087e43"><td class="mdescLeft">&#160;</td><td class="mdescRight">The condition value.  <br /></td></tr>
<tr class="separator:aee79bc725669f841f5bb2bf1dd087e43"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a0a92d2008c3871d6ca8b13c4f5ebe624" name="a0a92d2008c3871d6ca8b13c4f5ebe624"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0a92d2008c3871d6ca8b13c4f5ebe624">&#9670;&#160;</a></span>remove()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void IDHCPGroupCondition::remove </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Remove this condition from the group. </p>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a id="a77f4e6ed9303da46c48c592bc3646470" name="a77f4e6ed9303da46c48c592bc3646470"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a77f4e6ed9303da46c48c592bc3646470">&#9670;&#160;</a></span>inclusive</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">attribute boolean IDHCPGroupCondition::inclusive</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Whether this is an inclusive or exclusive group membership condition. </p>

</div>
</div>
<a id="a6c44c595fc7fbc63402b1ae2bda3985d" name="a6c44c595fc7fbc63402b1ae2bda3985d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a6c44c595fc7fbc63402b1ae2bda3985d">&#9670;&#160;</a></span>type</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">attribute <a class="el" href="_virtual_box_8idl.html#ad64816f3f460618a142d3ec78348668f">DHCPGroupConditionType</a> IDHCPGroupCondition::type</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Defines how the <a class="el" href="interface_i_d_h_c_p_group_condition.html#aee79bc725669f841f5bb2bf1dd087e43">IDHCPGroupCondition::value</a><b></b> is interpreted. </p>

</div>
</div>
<a id="aee79bc725669f841f5bb2bf1dd087e43" name="aee79bc725669f841f5bb2bf1dd087e43"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aee79bc725669f841f5bb2bf1dd087e43">&#9670;&#160;</a></span>value</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">attribute wstring IDHCPGroupCondition::value</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>The condition value. </p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.6
</small></address>
</body>
</html>
